version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/venv  # Exclude virtual environment from volume mount
    environment:
      - DEBUG=True
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
      - "5678:5678"  # For debugging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery:
    volumes:
      - .:/app
      - /app/venv
    environment:
      - DEBUG=True
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery-beat:
    volumes:
      - .:/app
      - /app/venv
    environment:
      - DEBUG=True
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
