# Generated by Django 5.0.6 on 2026-02-23 15:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Room number')),
                ('name', models.CharField(max_length=100, verbose_name='Room name / title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per night (USD)')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity (number of beds)')),
                ('num_seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of seats')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is available for booking')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['number'],
                'indexes': [models.Index(fields=['price_per_night'], name='room_price_idx'), models.Index(fields=['capacity'], name='room_capacity_idx'), models.Index(fields=['num_seats'], name='room_seats_idx'), models.Index(fields=['is_active'], name='room_active_idx')],
            },
        ),
    ]
