# Generated by Django 5.0.6 on 2026-02-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='room_seats_idx',
        ),
        migrations.RemoveField(
            model_name='room',
            name='num_seats',
        ),
    ]
